feat:
  ==: Feat
  id: db7cd5ca-cba4-4880-879a-c7b7b79d35ca
  name: Prodigy
  source: XGE
  page: 75
  other-sources: []
  entries:
    - ==: FeatStringEntry
      value: "You have a knack for learning new things. You gain the following
        benefits:"
    - ==: FeatListEntry
      items:
        - You gain one {@table skills|phb|skill proficiency} of your choice, one
          {@filter tool proficiency|items|type=tool;artisan's tools} of your
          choice, and fluency in one language of your choice.
        - Choose one skill in which you have proficiency. You gain expertise
          with that skill, which means your proficiency bonus is doubled for any
          ability check you make with it. The skill you choose must be one that
          isn't already benefiting from a feature, such as Expertise, that
          doubles your proficiency bonus.
