==: Spell
id: b3587409-a75f-438e-b5b2-53b557133741
name: Produce Flame
source: PHB
page: 269
srd: true
level: 0
school: CONJURATION
time:
  - ==: SpellTime
    number: 1
    unit: ACTION
range:
  ==: PointSpellRange
  distance:
    ==: SpellRangeDistanceSelf
components:
  ==: SpellComponentsWithNoMaterial
  somatic: true
  verbal: true
duration:
  - ==: TimedSpellDuration
    type: MINUTE
    amount: 10
entries:
  - ==: StringSpellEntry
    value: A flickering flame appears in your hand. The flame remains there for the
      duration and harms neither you nor your equipment. The flame sheds bright
      light in a 10-foot radius and dim light for an additional 10 feet. The
      spell ends if you dismiss it as an action or if you cast it again.
  - ==: StringSpellEntry
    value: You can also attack with the flame, although doing so ends the spell.
      When you cast this spell, or as an action on a later turn, you can hurl
      the flame at a creature within 30 feet of you. Make a ranged spell attack.
      On a hit, the target takes {@damage 1d8} fire damage.
  - ==: StringSpellEntry
    value: This spell's damage increases by {@dice 1d8} when you reach 5th level
      ({@damage 2d8}), 11th level ({@damage 3d8}), and 17th level ({@damage
      4d8}).
scaling-level-dice:
  - ==: SpellScalingLevelDice
    label: fire damage
    scaling:
      "1": 1d8
      "5": 2d8
      "11": 3d8
      "17": 4d8
damage-inflict:
  - FIRE
spell-attack:
  - RANGED
misc-tags:
  - CREATES_LIGHT
  - SCALING_EFFECTS
area-tags:
  - SINGLE_TARGET
